// Generate the implemented overview from Drizzle's snapshot; render with Mermaid CLI.
import { readFileSync, writeFileSync } from "node:fs";
const { tables } = JSON.parse(
  readFileSync(
    new URL("../src/migrations/meta/0002_snapshot.json", import.meta.url),
  ),
);
let diagram =
  "%% Implemented dsgnrd schema; generated by scripts/render-schema.mjs\nerDiagram\n    direction TB\n";
for (const [name, table] of Object.entries(tables)) {
  const foreign = new Set(
    Object.values(table.foreignKeys).flatMap((f) => f.columnsFrom),
  );
  diagram += `    ${name} {\n`;
  for (const column of Object.values(table.columns)) {
    const key = column.primaryKey
      ? " PK"
      : foreign.has(column.name)
        ? " FK"
        : "";
    const note =
      !column.notNull && !column.primaryKey
        ? ' "nullable"'
        : ["created", "updated"].includes(column.name)
          ? ' "timestamp"'
          : "";
    diagram += `        ${column.type} ${column.name}${key}${note}\n`;
  }
  diagram += "    }\n";
  for (const fk of Object.values(table.foreignKeys)) {
    const optional = !table.columns[fk.columnsFrom[0]].notNull;
    diagram += `    ${fk.tableTo} ${optional ? "|o" : "||"}--o{ ${name} : "${fk.columnsFrom.join(", ")}"\n`;
  }
}
writeFileSync(
  new URL("../docs/diagrams/dsgnrd-current.mmd", import.meta.url),
  diagram,
);
